- id: '1687752379058'
  alias: Повітряна Тривога
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.lvivska_oblast_air
    from: unknown
    to: 'on'
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      message: Увага Тривога
  mode: single
