# automation:
#   # Turns on lights 1 hour before sunset if people are home
#   # and if people get home between 16:00-23:00
#   - alias: "Rule 1 Light on in the evening"
#     trigger:
#       # Prefix the first line of each trigger configuration
#       # with a '-' to enter multiple
#       - platform: state
#         entity_id: input_boolean.kitchen_on
#     action:
#       # With a single service call, we don't need a '-' before service - though you can if you want to
#       - service: homeassistant.turn_on
#         target:
#           entity_id: group.living_room
