- alias: "Rule 1 Light on in the evening"
  trigger:
    - platform: state
      entity_id:
        - input_number.kitchen_night_max
        - input_number.kitchen_day_max

  action:
    entity_id:
      - input_boolean.kitchen_on
    service: >
      {%- if states('input_number.kitchen_night_max')|int > states('sensor.ble_temperature_kitchen')|int %}input_boolean.turn_on
      {% else %} input_boolean.turn_off {% endif %}
