# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  time_zone: Europe/Kiev

# Text to speech
tts:
  - platform: google_translate

history:

lovelace:
  mode: yaml
  resources: !include resources.yaml

# input_number: !include input_number.yaml
# input_boolean: !include input_boolean.yaml
# input_datetime: !include input_datetime.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensor.yaml
recorder: !include recorder.yaml
# ble_monitor: !include ble_monitor.yaml
