- platform: systemmonitor
  resources:
    - type: processor_use
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: last_boot
    - type: disk_free
      arg: /

- platform: filesize
  # name: home_assistant_v2_db
  file_paths:
    - /config/home-assistant_v2.db

- platform: sql
  db_url: mysql://hass:hass@core-mariadb/homeassistant?charset=utf8
  queries:
    - name: Maria DB size
      query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1048576, 2) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
      column: "value"
      unit_of_measurement: MB

- platform: time_date
  display_options:
    - "time"
    - "date"
    - "date_time"
    - "time_date"

- platform: command_line
  name: cpu_temp
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ (value | multiply(0.001)) | round(1) }}"

- platform: rest
  resource: http://192.168.0.70:8123/api/states/sensor.online_custom
  name: main_state
  force_update: true
  headers:
    Authorization: ""
    content-type: "application/json"
  value_template: "{{ value_json.state }}"

- platform: rest
  resource: http://192.168.0.71:8123/api/states/sensor.online_custom
  name: reserve_state
  force_update: true
  headers:
    Authorization: ""
    content-type: "application/json"
  value_template: "{{ value_json.state }}"
