title: My Awesome Home
views:
  # View tab title.

  - title: Загальні
    # Unique path for direct access /lovelace/${path}

    cards:
      - type: entities
        show_header_toggle: false

        title: Котел
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: input_boolean.kotel_haz_on_off
            name: Газовий котел

          - entity: input_boolean.kotel_elektrika_on_off
            name: Електричний котел

      - type: "custom:content-card-example"
        entities:
          - entity: Кухня
            button: input_boolean.kitchen_btn
            button_relay: switch.switch_relay1
            temperature: sensor.ble_temperature_kitchen
            night_temperature: input_number.kitchen_night_max
            day_temperature: input_number.kitchen_day_max

          - entity: Спал
            button: input_boolean.spalnya_btn
            button_relay: switch.switch_relay2
            temperature: sensor.ble_temperature_spalnya
            night_temperature: input_number.spalnya_night_max
            day_temperature: input_number.spalnya_day_max

          - entity: Майст
            button: input_boolean.maysternya_btn
            button_relay: switch.switch_relay3
            temperature: sensor.ble_temperature_maysternya
            night_temperature: input_number.maysternya_night_max
            day_temperature: input_number.maysternya_day_max

          - entity: Ванн
            button: input_boolean.vanna_btn
            button_relay: switch.switch_relay4
            temperature: sensor.ble_temperature_vanna
            night_temperature: input_number.vanna_night_max
            day_temperature: input_number.vanna_day_max

          - entity: Вел
            button: input_boolean.velika_btn
            button_relay: switch.switch_relay5
            temperature: sensor.ble_temperature_velika
            night_temperature: input_number.velika_night_max
            day_temperature: input_number.velika_day_max

          - entity: Ані
            button: input_boolean.ani_btn
            button_relay: switch.switch_relay6
            temperature: sensor.ble_temperature_ani
            night_temperature: input_number.ani_night_max
            day_temperature: input_number.ani_day_max

          - entity: Кор
            button: input_boolean.koridor_btn
            button_relay: switch.switch_relay7
            temperature: sensor.ble_temperature_koridor
            night_temperature: input_number.koridor_night_max
            day_temperature: input_number.koridor _day_max

      # Entities card will take a list of entities and show their state.
      - type: entities
        show_header_toggle: false
        # Title of the entities card
        title: Котел Газовий
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: switch.switch_d0
            name: Реле котел

          - entity: sensor.temperature_test2
            name: Котел вихід

          - entity: sensor.temperature_test1
            name: Котел обратка

      - type: entities
        show_header_toggle: false
        # Title of the entities card
        title: Котел Електричний
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: switch.switch_relay0
            name: Реле електричний котел
          - entity: input_boolean.kolektor_nasos_on_off

      - type: entities
        show_header_toggle: false

        title: Віртуальні
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: input_boolean.kotel_haz_on_off
          - entity: input_boolean.kotel_elektrika_on_off
          - entity: input_boolean.hoch_odna
          - entity: input_boolean.kolektor_nasos_on_off

          - entity: input_boolean.kitchen_btn
            name: Кухня

          - entity: input_boolean.spalnya_btn
            name: Спальня

          - entity: input_boolean.maysternya_btn
            name: Майстерня

          - entity: input_boolean.vanna_btn
            name: Ванна

          - entity: input_boolean.velika_btn
            name: Вітальня

          - entity: input_boolean.ani_btn
            name: Ані

          - entity: input_boolean.koridor_btn
            name: Коридор

      - type: entities
        show_header_toggle: false
        # Title of the entities card

        title: Колектор (не міняти рід онлі)
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: switch.switch_relay1
            name: Кухня

          - entity: switch.switch_relay2
            name: Спальня

          - entity: switch.switch_relay3
            name: Майстерня

          - entity: switch.switch_relay4
            name: Ванна

          - entity: switch.switch_relay5
            name: Вітальня

          - entity: switch.switch_relay6
            name: Ані

          - entity: switch.switch_relay7
            name: Коридор

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.

    # The cards to show on this view.

  - title: Детальні
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            # Title of the entities card
            title: Кухня
            show_header_toggle: false

            entities:
              - entity: input_boolean.kitchen_btn
              - entity: switch.switch_relay1
              - entity: sensor.ble_temperature_kitchen
                name: Температура
              - entity: sensor.ble_battery_kitchen
                name: Батарейка
              - entity: input_number.kitchen_night_max
              - entity: input_number.kitchen_day_max
              - entity: input_datetime.kitchen_start
              - entity: input_datetime.kitchen_end

          - type: entities
            # Title of the entities card
            title: Спальня
            show_header_toggle: false

            entities:
              - entity: input_boolean.spalnya_btn
              - entity: switch.switch_relay2
              - entity: sensor.ble_temperature_spalnya
                name: Температура
              - entity: sensor.ble_battery_spalnya
                name: Батарейка
              - entity: input_number.spalnya_night_max
              - entity: input_number.spalnya_day_max

              - entity: input_datetime.spalnya_start
              - entity: input_datetime.spalnya_end

          - type: entities
            # Title of the entities card
            title: Майстерня
            show_header_toggle: false

            entities:
              - entity: input_boolean.maysternya_btn
              - entity: switch.switch_relay3
              - entity: sensor.ble_temperature_maysternya
                name: Температура
              - entity: sensor.ble_battery_maysternya
                name: Батарейка
              - entity: input_number.maysternya_night_max
              - entity: input_number.maysternya_day_max

              - entity: input_datetime.maysternya_start
              - entity: input_datetime.maysternya_end

          - type: entities
            # Title of the entities card
            title: Ванна
            show_header_toggle: false

            entities:
              - entity: input_boolean.vanna_btn
              - entity: switch.switch_relay4
              - entity: sensor.ble_temperature_vanna
                name: Температура
              - entity: sensor.ble_battery_vanna
                name: Батарейка
              - entity: input_number.vanna_night_max
              - entity: input_number.vanna_day_max

              - entity: input_datetime.vanna_start
              - entity: input_datetime.vanna_end

          - type: entities
            # Title of the entities card
            title: Велика
            show_header_toggle: false

            entities:
              - entity: input_boolean.velika_btn
              - entity: switch.switch_relay5
              - entity: sensor.ble_temperature_velika
                name: Температура
              - entity: sensor.ble_battery_velika
                name: Батарейка
              - entity: input_number.velika_night_max
              - entity: input_number.velika_day_max

              - entity: input_datetime.velika_start
              - entity: input_datetime.velika_end

          - type: entities
            # Title of the entities card
            title: Ані
            show_header_toggle: false

            entities:
              - entity: input_boolean.ani_btn
              - entity: switch.switch_relay6
              - entity: sensor.ble_temperature_ani
                name: Температура
              - entity: sensor.ble_battery_ani
                name: Батарейка
              - entity: input_number.ani_night_max
              - entity: input_number.ani_day_max

              - entity: input_datetime.ani_start
              - entity: input_datetime.ani_end

          - type: entities
            # Title of the entities card
            title: Коридор
            show_header_toggle: false

            entities:
              - entity: input_boolean.koridor_btn
              - entity: switch.switch_relay7
              - entity: sensor.ble_temperature_koridor
                name: Температура
              - entity: sensor.ble_battery_koridor
                name: Батарейка
              - entity: input_number.koridor_night_max
              - entity: input_number.koridor_day_max

              - entity: input_datetime.koridor_start
              - entity: input_datetime.koridor_end

          - type: entities
            # Title of the entities card
            title: Дах
            show_header_toggle: false

            entities:
              - entity: sensor.ble_temperature_dax
                name: Температура
              - entity: sensor.ble_battery_dax
                name: Батарейка

          - type: entities
            # Title of the entities card
            title: Proektor
            show_header_toggle: false

            entities:
              - entity: sensor.ble_temperature_proektor
                name: Температурa
              - entity: sensor.ble_battery_proektor
                name: Батарейка

          - type: entities
            # Title of the entities card
            title: Вулиця
            show_header_toggle: false

            entities:
              - entity: sensor.ble_temperature_vulichya
                name: Температурa
              - entity: sensor.ble_battery_vulichya
                name: Батарейка

  - title: Система
    cards:
      # Entities card will take a list of entities and show their state.
      - type: markdown
        content: >
          **Система**
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: gauge
                name: Загрузка CPU
                unit: "%"
                entity: sensor.processor_use
                severity:
                  green: 0
                  yellow: 60
                  red: 85

              - type: gauge
                name: Загрузка ОЗУ
                unit: "%"
                entity: sensor.memory_use_percent
                severity:
                  green: 0
                  yellow: 60
                  red: 85

          - type: horizontal-stack
            cards:
              - type: gauge
                name: Температура ЦПУ
                unit: "C"
                entity: sensor.cpu_temp
                severity:
                  green: 0
                  yellow: 60
                  red: 85

      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              **Cостояние серверов**
          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.main_state
                name: Raspberry Pi 3 B+ в онлайне -
                icon: mdi:clock-outline
              - entity: sensor.reserve_state
                name: Khadas VIM2 в онлайне -
                icon: mdi:clock-outline

          - type: entities
            show_header_toggle: false
            entities:
              - entity: sensor.time
                name: Текущее время -
                icon: mdi:clock
                secondary_info: entity-id
              - entity: sensor.date
                name: Дата -
                icon: mdi:calendar
                secondary_info: entity-id
              - entity: sensor.home_assistant_v2_db
                name: Объем базы данных HA -
                icon: mdi:database
                secondary_info: entity-id
              - entity: sensor.maria_db_size
                name: Объем базы данных Maria -
                icon: mdi:database
                secondary_info: entity-id
              - type: divider
              - type: call-service
                icon: mdi:database-minus
                name: База данных
                action_name: Сжать
                service: recorder.purge
                service_data:
                  keep_days: 1
                  repack: true

  - title: Графіки
    cards:
      - type: history-graph
        title: "Температура"
        entities:
          - entity: sensor.ble_temperature_kitchen
            name: Кухня
          - entity: sensor.ble_temperature_spalnya
            name: Спальня

          - entity: sensor.ble_temperature_maysternya
            name: Майстерня

          - entity: sensor.ble_temperature_vanna
            name: Ванна

          - entity: sensor.ble_temperature_velika
            name: Велика

          - entity: sensor.ble_temperature_ani
            name: Ані

          - entity: sensor.ble_temperature_koridor
            name: Коридор

          - entity: sensor.ble_temperature_dax
            name: Дах

          - entity: sensor.ble_temperature_proektor
            name: Проектор

          - entity: sensor.ble_temperature_vulichya
            name: Вулиця

      - type: history-graph
        title: "Кухня"
        entities:
          - entity: sensor.ble_temperature_kitchen

      - type: history-graph
        title: "Спальня"
        entities:
          - entity: sensor.ble_temperature_spalnya

      - type: history-graph
        title: "Майстерня"
        entities:
          - entity: sensor.ble_temperature_maysternya

      - type: history-graph
        title: "Ванна"
        entities:
          - entity: sensor.ble_temperature_vanna

      - type: history-graph
        title: "Велика"
        entities:
          - entity: sensor.ble_temperature_velika

      - type: history-graph
        title: "Ані"
        entities:
          - entity: sensor.ble_temperature_ani

      - type: history-graph
        title: "Коридор"
        entities:
          - entity: sensor.ble_temperature_koridor

      - type: history-graph
        title: "Дах"
        entities:
          - entity: sensor.ble_temperature_dax

      - type: history-graph
        title: "Проектор"
        entities:
          - entity: sensor.ble_temperature_proektor

      - type: history-graph
        title: "Вулиця"
        entities:
          - entity: sensor.ble_temperature_vulichya

  - title: UI Lovelace
    cards:
      # Entities card will take a list of entities and show their state.
      - type: entities
        # Title of the entities card
        title: Example
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - light.kitchen
          - switch.ac
          - entity: light.living_room
            # Override the name to use
            name: LR Lights

        # The markdown card will render markdown text.
      - type: markdown
        title: Lovelace
        content: >
          Welcome to your **Lovelace UI**.
