title: My Awesome Home
views:
  # View tab title.

  - title: Загальні
    # Unique path for direct access /lovelace/${path}

    cards:
      - type: gauge
        name: Генерація
        unit: "%"
        entity: sensor.solar_energy_diff_in_percentage
        segments:
          - from: 90
            color: "#43a047"

      - type: gauge
        name: Генерація VA
        unit: "%"
        entity: sensor.pzem_reactive_va_diff_in_percentage
        segments:
          - from: 90
            color: "#43a047"

      - type: entities
        show_header_toggle: false

        title: Інвертор Вхід
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: sensor.pzem_004t_1_v3_power
          - entity: sensor.pzem_energy_reactive_va_1
          - entity: switch.220v_energy_reset_1
          - entity: sensor.pzem_004t_1_v3_energy
          - entity: sensor.220v_total_daily_energy_1
          - entity: sensor.220v_total_daily_energy_reactive_1
          - entity: sensor.pzem_004t_1_v3_current
          - entity: sensor.pzem_004t_1_v3_frequency
          - entity: sensor.pzem_004t_1_v3_power_factor
          - entity: sensor.pzem_004t_1_v3_voltage

      - type: entities
        show_header_toggle: false

        title: Інвертор Вихід
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: sensor.pzem_004t_2_v3_power
          - entity: sensor.pzem_energy_reactive_va_2
          - entity: switch.220v_energy_reset_2
          - entity: sensor.pzem_004t_2_v3_energy
          - entity: sensor.220v_total_daily_energy_2
          - entity: sensor.220v_total_daily_energy_reactive_2
          - entity: sensor.pzem_004t_2_v3_current
          - entity: sensor.pzem_004t_2_v3_frequency
          - entity: sensor.pzem_004t_2_v3_power_factor
          - entity: sensor.pzem_004t_2_v3_voltage

      - type: entities
        show_header_toggle: false
        title: Сонячні панелі
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: switch.switch_solar_meter_restart_esp
            name: Рестарт ЕSP

          - entity: sensor.solar_energy_diff
            name: Генерація

          - entity: sensor.pzem_reactive_va_diff
            name: Генерація (VA)

          - entity: sensor.total_dayly_energy_diff
            name: Всього за день

          - entity: sensor.total_dayly_energy_reactive_diff
            name: Всього за день (VA)

          - entity: sensor.pzem_004t_1_v3_power
            name: Вхід

          - entity: sensor.pzem_004t_2_v3_power
            name: Вихід

          - entity: switch.switch_relay_0
            name: Реле 1квт
          - entity: switch.switch_relay_1
            name: Реле 1квт
          - entity: switch.switch_relay_2
            name: Реле 1квт

      # - type: "custom:content-card-example"
      #   entities:
      #     - entity: Кухня
      #       button_relay: switch.switch_relay_v2_d4
      #       temperature: sensor.ble_temperature_kitchen
      #       night_temperature: input_number.kitchen_night_max
      #       day_temperature: input_number.kitchen_day_max

      #     - entity: Спальня
      #       button_relay: switch.switch_relay_v2_d5
      #       temperature: sensor.ble_temperature_v2_spalnya
      #       night_temperature: input_number.spalnya_night_max
      #       day_temperature: input_number.spalnya_day_max

      #     - entity: Майстерня
      #       button_relay: switch.switch_relay_v2_d6
      #       temperature: sensor.ble_temperature_v2_maysternya
      #       night_temperature: input_number.maysternya_night_max
      #       day_temperature: input_number.maysternya_day_max

      #     - entity: Ванна
      #       button_relay: switch.switch_relay_v2_d7
      #       temperature: sensor.ble_temperature_v2_vanna
      #       night_temperature: input_number.vanna_night_max
      #       day_temperature: input_number.vanna_day_max

      #     - entity: Велика
      #       button_relay: switch.switch_relay_v2_d8
      #       temperature: sensor.ble_temperature_v2_velika
      #       night_temperature: input_number.velika_night_max
      #       day_temperature: input_number.velika_day_max

      #     - entity: Ані
      #       button_relay: switch.switch_relay_v2_d9
      #       temperature: sensor.ble_temperature_v2_ani
      #       night_temperature: input_number.ani_night_max
      #       day_temperature: input_number.ani_day_max

      #     - entity: Коридор
      #       button_relay: switch.switch_relay_v2_d10
      #       temperature: sensor.ble_temperature_v2_koridor
      #       night_temperature: input_number.koridor_night_max
      #       day_temperature: input_number.koridor_day_max

      - type: entities
        show_header_toggle: false
        title: Температура
        entities:
          - entity: sensor.ble_temperature_kitchen_2
            name: Кухня

          - entity: sensor.ble_temperature_spalnya_2
            name: Спальня

          - entity: sensor.ble_temperature_maysternya_2
            name: Майстерня

          - entity: sensor.ble_temperature_vanna_2
            name: Ванна

          - entity: sensor.ble_temperature_velika_2
            name: Велика

          - entity: sensor.ble_temperature_ani_2
            name: Ані

          - entity: sensor.ble_temperature_koridor_2
            name: Коридор

          - entity: sensor.ble_temperature_dax_2
            name: Дах

          - entity: sensor.ble_temperature_proektor
            name: Проектор

          - entity: sensor.ble_temperature_vulichya
            name: Вулиця

      - type: entities
        show_header_toggle: false
        title: Колектор (esphome)
        entities:
          - entity: switch.switch_relay_d1_electro_kotel
            name: Елктро-котел

          - entity: switch.switch_relay_d12_haz_zamikannya
            name: Газ (замикання)

          - entity: switch.switch_relay_d3_nasos
            name: Насос

          - entity: switch.switch_relay_d2_vhid_niz
            name: Вхід Низ

          - entity: switch.switch_relay_d4_kitchen
            name: Кухня

          - entity: switch.switch_relay_d5_spalnya
            name: Спальня

          - entity: switch.switch_relay_d6_maysternya
            name: Майстерня

          - entity: switch.switch_relay_d7_vanna
            name: Ванна

          - entity: switch.switch_relay_d8_velika
            name: Вітальня

          - entity: switch.switch_relay_d9_ani
            name: Ані

          - entity: switch.switch_relay_d10_koridor
            name: Коридор

  - title: Детальні
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Кухня
            show_header_toggle: false

            entities:
              - entity: switch.switch_relay_d4_kitchen
                name: Реле
              - entity: sensor.ble_temperature_kitchen_2
                name: Температура
              - entity: sensor.ble_battery_kitchen_2
                name: Батарейка

          - type: entities
            title: Спальня
            show_header_toggle: false

            entities:
              - entity: switch.switch_relay_d5_spalnya
                name: Реле
              - entity: sensor.ble_temperature_spalnya_2
                name: Температура
              - entity: sensor.ble_battery_spalnya_2
                name: Батарейка

          - type: entities
            title: Майстерня
            show_header_toggle: false

            entities:
              - entity: switch.switch_relay_d6_maysternya
                name: Реле
              - entity: sensor.ble_temperature_maysternya_2
                name: Температура
              - entity: sensor.ble_battery_maysternya_2
                name: Батарейка

          - type: entities
            title: Ванна
            show_header_toggle: false

            entities:
              - entity: switch.switch_relay_d7_vanna
                name: Реле
              - entity: sensor.ble_temperature_vanna_2
                name: Температура
              - entity: sensor.ble_battery_vanna_2
                name: Батарейка

          - type: entities
            title: Велика
            show_header_toggle: false

            entities:
              - entity: switch.switch_relay_d8_velika
                name: Реле
              - entity: sensor.ble_temperature_velika_2
                name: Температура
              - entity: sensor.ble_battery_velika_2
                name: Батарейка

          - type: entities
            title: Ані
            show_header_toggle: false

            entities:
              - entity: switch.switch_relay_d9_ani
                name: Реле
              - entity: sensor.ble_temperature_ani_2
                name: Температура
              - entity: sensor.ble_battery_ani_2
                name: Батарейка

          - type: entities
            title: Коридор
            show_header_toggle: false

            entities:
              - entity: switch.switch_relay_d10_koridor
                name: Реле
              - entity: sensor.ble_temperature_koridor_2
                name: Температура
              - entity: sensor.ble_battery_koridor_2
                name: Батарейка

          - type: entities
            title: Дах
            show_header_toggle: false

            entities:
              - entity: sensor.ble_temperature_dax_2
                name: Температура
              - entity: sensor.ble_battery_dax_2
                name: Батарейка

          - type: entities
            title: Проектор
            show_header_toggle: false

            entities:
              - entity: sensor.ble_temperature_proektor
                name: Температурa
              - entity: sensor.ble_battery_proektor
                name: Батарейка

          - type: entities
            title: Вулиця
            show_header_toggle: false

            entities:
              - entity: sensor.ble_temperature_vulichya
                name: Температурa
              - entity: sensor.ble_battery_vulichya
                name: Батарейка

  - title: Графіки
    cards:
      - type: history-graph
        title: "Температура"
        entities:
          - entity: sensor.ble_temperature_v2_kitchen
            name: Кухня
          - entity: sensor.ble_temperature_v2_spalnya
            name: Спальня

          - entity: sensor.ble_temperature_v2_maysternya
            name: Майстерня

          - entity: sensor.ble_temperature_v2_vanna
            name: Ванна

          - entity: sensor.ble_temperature_v2_velika
            name: Велика

          - entity: sensor.ble_temperature_v2_ani
            name: Ані

          - entity: sensor.ble_temperature_v2_koridor
            name: Коридор

          - entity: sensor.ble_temperature_v2_dax
            name: Дах

          - entity: sensor.ble_temperature_v2_proektor
            name: Проектор

          - entity: sensor.ble_temperature_v2_vulichya
            name: Вулиця

      - type: history-graph
        title: "Кухня"
        entities:
          - entity: sensor.ble_temperature_v2_kitchen

      - type: history-graph
        title: "Спальня"
        entities:
          - entity: sensor.ble_temperature_v2_spalnya

      - type: history-graph
        title: "Майстерня"
        entities:
          - entity: sensor.ble_temperature_v2_maysternya

      - type: history-graph
        title: "Ванна"
        entities:
          - entity: sensor.ble_temperature_v2_vanna

      - type: history-graph
        title: "Велика"
        entities:
          - entity: sensor.ble_temperature_v2_velika

      - type: history-graph
        title: "Ані"
        entities:
          - entity: sensor.ble_temperature_v2_ani

      - type: history-graph
        title: "Коридор"
        entities:
          - entity: sensor.ble_temperature_v2_koridor

      - type: history-graph
        title: "Дах"
        entities:
          - entity: sensor.ble_temperature_v2_dax

      - type: history-graph
        title: "Проектор"
        entities:
          - entity: sensor.ble_temperature_v2_proektor

      - type: history-graph
        title: "Вулиця"
        entities:
          - entity: sensor.ble_temperature_v2_vulichya
