title: My Awesome Home
views:
  # View tab title.

  - title: Загальні
    # Unique path for direct access /lovelace/${path}

    cards:
      - type: entities
        show_header_toggle: false

        title: Акумулятор
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: switch.switch_invertor
            name: Інвертор (автоматично)

          - entity: switch.switch_zaryadka
            name: Зарядка (автоматично)

          - entity: sensor.battery_voltage
            name: Напруга

          # - entity: input_number.battery_percentage
          #   name: Рівень заряду у відсотках

          # - entity: switch.invertor
          #   name: Інвертор
          # - entity: sensor.invertor_current_power
          #   name: Інвертор споживання

      - type: entities
        show_header_toggle: false

        title: Котел
        # The entities here will be shown in the same order as specified.
        # Each entry is an entity ID or a map with extra options.
        entities:
          - entity: input_boolean.kotel_haz_on_off
            name: Газовий котел (віртуальна)

          - entity: input_boolean.kotel_haz_eko
            name: Еко режим

          - entity: input_boolean.kotel_elektrika_on_off
            name: Електричний котел (віртуальна)

      - type: "custom:content-card-example"
        entities:
          - entity: Кухня
            button: input_boolean.kitchen_btn
            button_relay: switch.switch_relay_v2_d4
            temperature: sensor.ble_temperature_v2_kitchen
            night_temperature: input_number.kitchen_night_max
            day_temperature: input_number.kitchen_day_max

          - entity: Спальня
            button: input_boolean.spalnya_btn
            button_relay: switch.switch_relay_v2_d5
            temperature: sensor.ble_temperature_v2_spalnya
            night_temperature: input_number.spalnya_night_max
            day_temperature: input_number.spalnya_day_max

          - entity: Майстерня
            button: input_boolean.maysternya_btn
            button_relay: switch.switch_relay_v2_d6
            temperature: sensor.ble_temperature_v2_maysternya
            night_temperature: input_number.maysternya_night_max
            day_temperature: input_number.maysternya_day_max

          - entity: Ванна
            button: input_boolean.vanna_btn
            button_relay: switch.switch_relay_v2_d7
            temperature: sensor.ble_temperature_v2_vanna
            night_temperature: input_number.vanna_night_max
            day_temperature: input_number.vanna_day_max

          - entity: Велика
            button: input_boolean.velika_btn
            button_relay: switch.switch_relay_v2_d8
            temperature: sensor.ble_temperature_v2_velika
            night_temperature: input_number.velika_night_max
            day_temperature: input_number.velika_day_max

          - entity: Ані
            button: input_boolean.ani_btn
            button_relay: switch.switch_relay_v2_d9
            temperature: sensor.ble_temperature_v2_ani
            night_temperature: input_number.ani_night_max
            day_temperature: input_number.ani_day_max

          - entity: Коридор
            button: input_boolean.koridor_btn
            button_relay: switch.switch_relay_v2_d10
            temperature: sensor.ble_temperature_v2_koridor
            night_temperature: input_number.koridor_night_max
            day_temperature: input_number.koridor_day_max

      - type: entities
        show_header_toggle: false
        title: Віртуальні
        entities:
          - entity: input_boolean.hoch_odna

          - entity: input_boolean.kitchen_btn
            name: Кухня

          - entity: input_boolean.spalnya_btn
            name: Спальня

          - entity: input_boolean.maysternya_btn
            name: Майстерня

          - entity: input_boolean.vanna_btn
            name: Ванна

          - entity: input_boolean.velika_btn
            name: Вітальня

          - entity: input_boolean.ani_btn
            name: Ані

          - entity: input_boolean.koridor_btn
            name: Коридор

      - type: entities
        show_header_toggle: false
        title: Колектор (esphome)
        entities:
          - entity: switch.switch_relay_v2_d1
            name: Елктро-котел

          - entity: switch.switch_relay_v2_d12
            name: Газ (замикання)

          - entity: switch.switch_relay_v2_d3
            name: Насос

          - entity: switch.switch_relay_v2_d2
            name: Вхід Низ

          - entity: switch.switch_relay_v2_d4
            name: Кухня

          - entity: switch.switch_relay_v2_d5
            name: Спальня

          - entity: switch.switch_relay_v2_d6
            name: Майстерня

          - entity: switch.switch_relay_v2_d7
            name: Ванна

          - entity: switch.switch_relay_v2_d8
            name: Вітальня

          - entity: switch.switch_relay_v2_d9
            name: Ані

          - entity: switch.switch_relay_v2_d10
            name: Коридор

  - title: Детальні
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            # Title of the entities card
            title: Кухня
            show_header_toggle: false

            entities:
              - entity: input_boolean.kitchen_btn
              - entity: switch.switch_relay_v2_d1
              - entity: sensor.ble_temperature_v2_kitchen
                name: Температура
              - entity: sensor.ble_battery_v2_kitchen
                name: Батарейка
              - entity: input_number.kitchen_night_max
              - entity: input_number.kitchen_day_max
              - entity: input_datetime.kitchen_start
              - entity: input_datetime.kitchen_end

          - type: entities
            # Title of the entities card
            title: Спальня
            show_header_toggle: false

            entities:
              - entity: input_boolean.spalnya_btn
              - entity: switch.switch_relay_v2_d2
              - entity: sensor.ble_temperature_v2_spalnya
                name: Температура
              - entity: sensor.ble_battery_v2_spalnya
                name: Батарейка
              - entity: input_number.spalnya_night_max
              - entity: input_number.spalnya_day_max

              - entity: input_datetime.spalnya_start
              - entity: input_datetime.spalnya_end

          - type: entities
            # Title of the entities card
            title: Майстерня
            show_header_toggle: false

            entities:
              - entity: input_boolean.maysternya_btn
              - entity: switch.switch_relay_v2_d3
              - entity: sensor.ble_temperature_v2_maysternya
                name: Температура
              - entity: sensor.ble_battery_v2_maysternya
                name: Батарейка
              - entity: input_number.maysternya_night_max
              - entity: input_number.maysternya_day_max

              - entity: input_datetime.maysternya_start
              - entity: input_datetime.maysternya_end

          - type: entities
            # Title of the entities card
            title: Ванна
            show_header_toggle: false

            entities:
              - entity: input_boolean.vanna_btn
              - entity: switch.switch_relay_v2_d4
              - entity: sensor.ble_temperature_v2_vanna
                name: Температура
              - entity: sensor.ble_battery_v2_vanna
                name: Батарейка
              - entity: input_number.vanna_night_max
              - entity: input_number.vanna_day_max

              - entity: input_datetime.vanna_start
              - entity: input_datetime.vanna_end

          - type: entities
            # Title of the entities card
            title: Велика
            show_header_toggle: false

            entities:
              - entity: input_boolean.velika_btn
              - entity: switch.switch_relay_v2_d5
              - entity: sensor.ble_temperature_v2_velika
                name: Температура
              - entity: sensor.ble_battery_v2_velika
                name: Батарейка
              - entity: input_number.velika_night_max
              - entity: input_number.velika_day_max

              - entity: input_datetime.velika_start
              - entity: input_datetime.velika_end

          - type: entities
            # Title of the entities card
            title: Ані
            show_header_toggle: false

            entities:
              - entity: input_boolean.ani_btn
              - entity: switch.switch_relay_v2_d6
              - entity: sensor.ble_temperature_v2_ani
                name: Температура
              - entity: sensor.ble_battery_v2_ani
                name: Батарейка
              - entity: input_number.ani_night_max
              - entity: input_number.ani_day_max

              - entity: input_datetime.ani_start
              - entity: input_datetime.ani_end

          - type: entities
            # Title of the entities card
            title: Коридор
            show_header_toggle: false

            entities:
              - entity: input_boolean.koridor_btn
              - entity: switch.switch_relay_v2_d7
              - entity: sensor.ble_temperature_v2_koridor
                name: Температура
              - entity: sensor.ble_battery_v2_koridor
                name: Батарейка
              - entity: input_number.koridor_night_max
              - entity: input_number.koridor_day_max

              - entity: input_datetime.koridor_start
              - entity: input_datetime.koridor_end

          - type: entities
            # Title of the entities card
            title: Дах
            show_header_toggle: false

            entities:
              - entity: sensor.ble_temperature_v2_dax
                name: Температура
              - entity: sensor.ble_battery_v2_dax
                name: Батарейка

          - type: entities
            # Title of the entities card
            title: Проектор
            show_header_toggle: false

            entities:
              - entity: sensor.ble_temperature_v2_proektor
                name: Температурa
              - entity: sensor.ble_battery_v2_proektor
                name: Батарейка

          - type: entities
            # Title of the entities card
            title: Вулиця
            show_header_toggle: false

            entities:
              - entity: sensor.ble_temperature_v2_vulichya
                name: Температурa
              - entity: sensor.ble_battery_v2_vulichya
                name: Батарейка

  - title: Графіки
    cards:
      - type: history-graph
        title: "Температура"
        entities:
          - entity: sensor.ble_temperature_v2_kitchen
            name: Кухня
          - entity: sensor.ble_temperature_v2_spalnya
            name: Спальня

          - entity: sensor.ble_temperature_v2_maysternya
            name: Майстерня

          - entity: sensor.ble_temperature_v2_vanna
            name: Ванна

          - entity: sensor.ble_temperature_v2_velika
            name: Велика

          - entity: sensor.ble_temperature_v2_ani
            name: Ані

          - entity: sensor.ble_temperature_v2_koridor
            name: Коридор

          - entity: sensor.ble_temperature_v2_dax
            name: Дах

          - entity: sensor.ble_temperature_v2_proektor
            name: Проектор

          - entity: sensor.ble_temperature_v2_vulichya
            name: Вулиця

      - type: history-graph
        title: "Кухня"
        entities:
          - entity: sensor.ble_temperature_v2_kitchen

      - type: history-graph
        title: "Спальня"
        entities:
          - entity: sensor.ble_temperature_v2_spalnya

      - type: history-graph
        title: "Майстерня"
        entities:
          - entity: sensor.ble_temperature_v2_maysternya

      - type: history-graph
        title: "Ванна"
        entities:
          - entity: sensor.ble_temperature_v2_vanna

      - type: history-graph
        title: "Велика"
        entities:
          - entity: sensor.ble_temperature_v2_velika

      - type: history-graph
        title: "Ані"
        entities:
          - entity: sensor.ble_temperature_v2_ani

      - type: history-graph
        title: "Коридор"
        entities:
          - entity: sensor.ble_temperature_v2_koridor

      - type: history-graph
        title: "Дах"
        entities:
          - entity: sensor.ble_temperature_v2_dax

      - type: history-graph
        title: "Проектор"
        entities:
          - entity: sensor.ble_temperature_v2_proektor

      - type: history-graph
        title: "Вулиця"
        entities:
          - entity: sensor.ble_temperature_v2_vulichya
